/* GENERATED by tools/gen-tier-stamps.py — do not edit.
 * Width divided by height of each tier stamp, whose artwork is cropped to
 * its lettering: TierBadge draws it CAP tall and aspect x CAP wide. Both
 * tours are built to one line, so the pairs match exactly. */
export default {
  atp: { 250: 5.5312, 500: 5.5938, 1000: 6.1094 },
  wta: { 250: 5.5312, 500: 5.5938, 1000: 6.1094 },
}

/* The ink each tour's artwork is flattened to: TOUR[*].text in
 * theme.js. Exported so a token change cannot silently leave the PNGs
 * behind — tierStamps.test.mjs compares the two. */
export const INK = { atp: '#8fb6ff', wta: '#ffb3c6' }
