/* GENERATED by tools/gen-tier-stamps.py — do not edit.
 * Width divided by height of each tier stamp, whose artwork is cropped to
 * its lettering: TierBadge draws it CAP tall and aspect x CAP wide. Both
 * tours are built to one line, so the pairs match exactly. */
export default {
  atp: { 250: 5.8818, 500: 5.9364, 1000: 6.4455 },
  wta: { 250: 5.8818, 500: 5.9364, 1000: 6.4455 },
}
